services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

volumes:
  postgres-data:

networks:
  app-network:
    name: app-network
    driver: bridge